### ISSUE TITLE
metronome-note structure is unreliable

### ISSUE THREAD

**Issue by GeorgeTailor** [w3c/musicxml#407] opened 2021-05-12 10:20 UTC
Hello all,
[Specification](https://w3c.github.io/musicxml/musicxml-reference/examples/metronome-note-element/) defines `triplet-feel` in an unreliable way. For example;
```
<direction placement="above">
   <direction-type>
      <metronome>
         <metronome-note>
            <metronome-type>eighth</metronome-type>
            <metronome-beam number="1">begin</metronome-beam>
         </metronome-note>
         <metronome-note>
            <metronome-type>eighth</metronome-type>
            <metronome-beam number="1">end</metronome-beam>
         </metronome-note>
         <metronome-relation>equals</metronome-relation>
         <metronome-note>
            <metronome-type>quarter</metronome-type>
            <metronome-tuplet bracket="yes" show-number="actual" type="start">
               <actual-notes>3</actual-notes>
               <normal-notes>2</normal-notes>
               <normal-type>eighth</normal-type>
            </metronome-tuplet>
         </metronome-note>
         <metronome-note>
            <metronome-type>eighth</metronome-type>
            <metronome-tuplet type="stop">
               <actual-notes>3</actual-notes>
               <normal-notes>2</normal-notes>
               <normal-type>eighth</normal-type>
            </metronome-tuplet>
         </metronome-note>
      </metronome>
   </direction-type>
   <sound>
      <swing>
         <first>2</first>
         <second>1</second>
      </swing>
   </sound>
</direction>
```

`direction.direction-type.metronome.metronome-note` is a single array for both normal notes, and the overriden ones. This makes determining where the normal ones ended and where is the override hard and unreliable.

I propose to change the structure to have separate properties: `normal` and `actual`, the same way tuplets are defined currently. The above example would look like this:
```
<direction placement="above">
   <direction-type>
      <metronome>
         <normal-note>
            <metronome-note>
               <metronome-type>eighth</metronome-type>
               <metronome-beam number="1">begin</metronome-beam>
            </metronome-note>
            <metronome-note>
               <metronome-type>eighth</metronome-type>
               <metronome-beam number="1">end</metronome-beam>
            </metronome-note>
         </normal-note>
         <actual-note>
            <metronome-note>
               <metronome-type>quarter</metronome-type>
               <metronome-tuplet bracket="yes" show-number="actual" type="start">
                  <actual-notes>3</actual-notes>
                  <normal-notes>2</normal-notes>
                  <normal-type>eighth</normal-type>
               </metronome-tuplet>
            </metronome-note>
            <metronome-note>
            <metronome-type>eighth</metronome-type>
               <metronome-tuplet type="stop">
                  <actual-notes>3</actual-notes>
                  <normal-notes>2</normal-notes>
                  <normal-type>eighth</normal-type>
               </metronome-tuplet>
            </metronome-note>
         </actual-note>
         <metronome-relation>equals</metronome-relation>
      </metronome>
   </direction-type>
   <sound>
      <swing>
         <first>2</first>
         <second>1</second>
      </swing>
   </sound>
</direction>
```

With the above structure it is easy to determine what should be overriden, for example, if we encounter two consecutive `eighth` notes as defined in `metronome.normal-note`, we know exactly what the override should be by looking at the `metronome.actual-note` array.

**Comment by mdgood** [comment] 2021-05-12 22:32
@GeorgeTailor Again, playback is represented in the `<swing>` element rather than the `<metronome-note>` element. This seems a near-duplicate of #406 with a different proposed solution, but the same underlying issue. I will close this issue. If there is something I am misunderstanding, please raise that in #406. Thanks!

**Closed as completed by mdgood** 2021-05-12 22:32 UTC
