### ISSUE TITLE
Accidentals not recognized

### ISSUE THREAD

**Issue by maxuke** [w3c/musicxml#179] opened 2017-02-26 17:17 UTC
Hi there,

I've created a piece of music in Sibelius 8.5 and used Dolet plugin to export MusicXML, which I then imported to Logic Pro 10.3. 

Everything looks good, until I realized that a punch of accidentals are not recognized, and midi notes are either half-step up or full octave and half step. 

Logic seems to have it's own transposition pre-settings, that were overruling my set concert pitch. But fixing the unrecognized accidentals is still a mystery. 

Any help how to approach this issue, cause I use a lot of accidentals in the sheet music.

Many tnx, 
A.

**Comment by mdgood** [comment] 2017-03-01 00:37
How does the score look like if you import it into Finale? This might give us an indication if it's a Dolet for Sibelius issue or a Logic issue.

This looks like a vendor software error rather than a MusicXML issue, so I will plan to close this issue out later this week. We could discuss this on the Music Notation Community Group mailing list, or you could file a technical support issue with either MakeMusic (for Dolet) or Apple (for Logic).

**Comment by maxuke** [comment] 2017-03-03 13:53
Actually, I was using an musicxml version generated by Sibelius 8.5 (which
then didn't transfer over accidentals in Logic Pro x 10.3.1).

But when I tried to export musicxml with Dolet 6.6 inside Sibelius, Logic
could NOT import the file at all, saying the UTF indicated on the first
line was not the same as the UTF in the rest of the file  - which is not
true, UTF in the xml file was same throughout.

Also it seemed that Logic had problems reading quotation marks - Dolet uses
' but Logic prefers to read "

Should I ask help from both Logic, cause importing musicxml is a very new
feature for the program, and Dolet developers ?

Regards,
Alari

**Comment by mogenslundholm** [comment] 2017-03-06 22:43
With the MusicXML-file uploaded it would be easy to identity who is to blame. A small example maybe even better. Could you upload such an example?

But this problem could be related to both #108 and #165 and #176. Item #108 takes up the question of automatic accidentals due to standard music rules (Which rules? "artexanis" asks). In item #176 "Webern" want to save an accidental as "automatic" or "frozen". As it is now, there is nothing wrong if the accidentals are wrong. It is just a matter of different music rules and a music notation program that "helps" you and puts the "right" accidentals instead of the accidentals you have. 

My proposal was to add a clarification to MusicXML specification(#176), that if an accidental is present, then it is mandatory. No accidental-specification means, that the notation program may use automatic rules. But then an empty accidental declaration is needed (e.g. &lt;accidental&gt;void&lt;/accidental&gt; or maybe just &lt;accidental/&gt;) to avoid automatic accidentals, where no accidental shall be there (no natural either)

**Comment by mdgood** [comment] 2017-03-07 06:57
Yes, this sounds like a Logic issue - unless you edited the MusicXML file in between exporting from Sibelius and importing into Logic.

**Comment by mdgood** [comment] 2019-03-18 17:14
Closing this as it is a software implementation issue. The potential root causes of the implementation issue are captured in other issues as @mogenslundholm notes.

**Closed as completed by mdgood** 2019-03-18 17:14 UTC
