### ISSUE TITLE
A question about the MusicXML scope

### ISSUE THREAD

**Issue by BerdinEge** [w3c/musicxml#313] opened 2020-05-04 09:51 UTC
I dont know there is correct place for this question but i have to. Is there a biggest possible scoped MusicXML sample to C# class mapping ? I am using a XML-to-C# serializer. I need a sample musicXML that includes all possible elements, attributes, values.

**Comment by mdgood** [comment] 2020-05-04 16:27
I would think you could generate the bindings from the schema file rather than a sample file. Could you provide more information about the tool that you are using? 

I don't know of any single MusicXML file that includes every possible feature - that would be a very large file indeed.

Note that we do plan to provide better documentation for using code generators as part of issue #280.

**Comment by BerdinEge** [comment] 2020-05-04 16:33
I use online XML serializer, there are lots of tools that handles this job. For an example this is what i used last:  https://xmltocsharp.azurewebsites.net/


Kimden: Michael Good<mailto:notifications@github.com>
Gönderilme: 4 Mayıs 2020 Pazartesi 19:28
Kime: w3c/musicxml<mailto:musicxml@noreply.github.com>
Bilgi: Berdin Ege Turgut<mailto:berdin_turgut@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [w3c/musicxml] A question about the MusicXML scope (#313)


I would think you could generate the bindings from the schema file rather than a sample file. Could you provide more information about the tool that you are using?

I don't know of any single MusicXML file that includes every possible feature - that would be a very large file indeed.

Note that we do plan to provide better documentation for using code generators as part of issue #280<https://github.com/w3c/musicxml/issues/280>.

**Comment by mdgood** [comment] 2020-05-12 15:11
I'm closing this as a duplicate of #280.

**Closed as completed by mdgood** 2020-05-12 15:11 UTC
