### ISSUE TITLE
Correct "cancel" documentation

### ISSUE THREAD

**Issue by ebrooks01** [w3c/musicxml#125] opened 2016-03-24 21:25 UTC
The XSD and web documentation (and perhaps others) for the "cancel" element read in part:

"The optional location attribute indicates whether the cancellation appears relative to the new key signature"

It should read:

"The optional location attribute indicates where the cancellation appears relative to the new key signature"

**Comment by mdgood** [comment] 2016-03-24 21:52
This appears to be a duplicate of #18 which is already fixed. Since it was closed and didn't have your correct Github ID, that would be easy to miss. I'm closing this but please reopen if I am missing something.

**Closed as completed by mdgood** 2016-03-24 21:52 UTC
Labels: documentation
